export enum InvocationType {
  UNKNOWN = 'UNKNOWN',
  BROWSER_ACTION = 'BROWSER_ACTION',
  BACKGROUND_PAGE = 'BACKGROUND_PAGE',
  CONTENT_SCRIPT = 'CONTENT_SCRIPT',
  OPTIONS_PAGE = 'OPTIONS_PAGE',
}
